site_name: NI-edu
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - python
nav:
    - Home: index.md
    - 'Getting started': installation.md
    - fMRI-introduction: fMRI-introduction.md
    - fMRI-pattern-analysis: fMRI-pattern-analysis.md

extra_css:
    - css/extra.css
